* vivmaniero/sched

ESPRIT Student? Harness the power of the shell to retrieve this week's schedule.

This repository hosts two scripts:
- [[file:src/sched_get.py][sched_get.py]]: authenticates through the website, and downloads the latest schedule.
- [[file:src/sched_extract.sh][sched_extract.sh]]: extracts the relevant schedule from the initial PDF and overwrites it.

These scripts have been tested to work on _Linux_, but they should
work just fine on _macOS_ as well. _Windows_ users should use [[https://docs.microsoft.com/en-us/windows/wsl/install][WSL]], as
I won't provide any support for any other methods.

** Prerequisites

+ =bash=
+ =moreutils=
+ =pdftk=
+ =pdfgrep=
+ =python3=
+ =python-requests=

** Usage

Navigate to the =src/= directory.
#+begin_src sh
cd src/
#+end_src

Open the =sched_get.py= file and modify the =username=, =password= and
=my_class= variables accordingly - you only have to do this once.

Run =sched_get.py=.
#+begin_src sh
python3 sched_get.py
#+end_src

=schedule.pdf= should now appear in your working directory.

** License

This software is licensed under [[file:LICENSE][the beerware license]].
