* vivmaniero/sched
ESPRIT Student? Harness the power of the shell to retrieve this week's schedule.

This repository hosts two scripts:
- [[file:src/sched_get.py][sched_get.py]]: authenticates through the website, and downloads the latest schedule.
- [[file:src/sched_extract.sh][sched_extract.sh]]: extracts the relevant schedule from the initial PDF and overwrites it.

These scripts have been tested to work on /Linux/, but they should
work just fine on /macOS/ as well. /Windows/ users should use [[https://docs.microsoft.com/en-us/windows/wsl/install][WSL]], as
I won't provide any support for any other methods.

** Prerequisites
+ =bash=
+ =moreutils=
+ =pdftk=
+ =pdfgrep=
+ =python3=
+ =python-requests=

** Usage
1. Navigate to the =src/= directory.
2. Specify your =username=, =password= and =class= in [[file:src/credentials.conf][credentials.conf]].
3. In your terminal emulator, run =python3 sched_get.py=.
4. Assuming your credentials are correct, =schedule.pdf= should now appear in your working directory.

** Copying
This software is subject to the terms of [[file:COPYING][the beerware license]].
